In [3]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((10,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full(10,4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [11]:
np.full((10,4), 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [12]:
a = np.array([1,3,4,5,6,10])
a[2]

4

In [14]:
# Similar to range in function
# Think of it as array-range
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
# 0 to 50 with 14 items
np.linspace(0,50,14)

array([ 0.        ,  3.84615385,  7.69230769, 11.53846154, 15.38461538,
       19.23076923, 23.07692308, 26.92307692, 30.76923077, 34.61538462,
       38.46153846, 42.30769231, 46.15384615, 50.        ])

In [23]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [25]:
# row, column 
n[1,1]

5

In [26]:
# no column gives entire row
n[0]

array([1, 2, 3])

In [28]:
# give entire column?
n[:,1]

array([2, 5, 8])

# Randomly generate data

In [30]:
# generates 5 row and 2 column random numbers between 0 - 1
np.random.randn(5,2)

array([[ 0.14639137, -0.55346007],
       [-0.271381  , -1.58928984],
       [-2.55020206, -0.63667234],
       [-0.25514563,  0.5252102 ],
       [-0.18464199, -0.57138075]])

In [34]:
# Reproducable random
np.random.seed(10)
np.random.randn(5,2)

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [35]:
# generate 5 row and 2 column random numbers between 1 - 100
np.random.randint(low=0,high=100, size=(5,2))

array([[62, 33],
       [72, 78],
       [49, 51],
       [54, 77],
       [69, 13]])

# Comparison operations

In [40]:
x = np.random.randint(low=1,high=1000, size=(10,5))
x > 100

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
x = np.random.randint(low=1,high=10, size=(4,2))
y = np.random.randint(low=1,high=20, size=?(4,2))
x > y

array([[ True,  True],
       [False, False],
       [ True,  True],
       [False, False]])

## Get all elements that are greater than in b

In [44]:
x = np.random.randint(low=1,high=20,size=(5,3))
y = np.random.randint(low=1,high=50, size=(5,3))
x[x>y]

array([15])

In [47]:
x.max(), x.min()

(19, 1)

In [48]:
y.max(), y.min()

(49, 10)

In [50]:
x.sum(), y.sum()

(152, 440)

In [51]:
x.std(), y.std()

(4.716872787015661, 13.097921802925667)

# Vector operations

In [62]:
x = np.random.randint(low=1,high=100,size=5)
y = np.random.randint(low=20,high=100, size=5)
x, y, x+y

(array([18, 60, 71, 64, 87]),
 array([49, 91, 39, 20, 27]),
 array([ 67, 151, 110,  84, 114]))

In [66]:
x = np.random.randint(low=2, high=100, size=10)
y = np.random.randint(low=10, high=100, size=(1,10))

In [76]:
y.transpose().shape

(10, 1)

In [74]:
x, y.transpose(), x.dot(y.transpose())

(array([81, 34, 71, 93, 18,  7, 65, 85, 77, 44]),
 array([[48],
        [67],
        [17],
        [98],
        [48],
        [58],
        [37],
        [74],
        [59],
        [19]]),
 array([31831]))

In [ ]:
np.eye()

In [4]:
x = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
    ])
y = np.array([1,0.5,2,1])

In [5]:
x.dot(y)

array([20. ,  6. ,  8.5])

In [12]:
y, y.T

(array([1. , 0.5, 2. , 1. ]), array([1. , 0.5, 2. , 1. ]))

In [14]:
y.T.dot(y)

6.25

In [15]:
x = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,1,2]
])
y = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])
x.dot(y)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 7. ,  7.5,  8. ]])